### ISSUE TITLE
composer.lock in .gitignore?

### ISSUE THREAD

**Issue by coditive-przemek-h** [coditive-com/firestarter-theme#13]
@coditive-pawel-m @coditive-tomek-g 

Guys, what about `composer.lock` in `.gitignore`? I've noticed that we pushed lockfile to main, but it shouldn't be there for new projects. But when someone will get this repo, they will have lockfile ignored and it might be crucial for the project. What do you think?

**Comment by coditive-tomek-g** [comment]
I think we should remove `compose.lock` from the repository, but not add it to the `.gitignore` and keep in mind that we can't push this file again to the repository.

**Comment by coditive-przemek-h** [comment]
Understood. We'll be checking this during PRs.
