### ISSUE TITLE
Add support for ACF blocks 

### ISSUE THREAD

**Issue by coditive-pawel-m** [coditive-com/firestarter-theme#2]

**Comment by coditive-przemek-h** [comment]
Hi Guys! I've created code that implements the following:

## Options

Add support for using `ACF Options` pages. When ACF is not enabled, it displays `WordPress` options page (but empty, so we need to take care of this in the future), but when enabled it uses `ACF` over `WP`. Currently, we have no support for local JSON, so we need to create such options from scratch. 

Important: We should access theme options using `fs()->settings()->get('setting')`. We should avoid using getting theme options using `get_option` or `get_field('', 'options')`. 

[description](https://github.com/coditive-com/firestarter-theme/tree/feature/add-support-for-acf-blocks#settings-1)

## Blocks

I've added support for the blocks module. It is described [here](https://github.com/coditive-com/firestarter-theme/tree/feature/add-support-for-acf-blocks#blocks). We can use blocks even without ACF.

## Other

It will be great if you check the comments and let me know what do you think. I haven't seen a response regarding my question about `readme.md` from the last PR so it will be also great if you let me know what do you think.

**Comment by coditive-pawel-m** [comment]
> but empty, so we need to take care of this in the future

Please create issues for all todos, even those small ones :) 

---

> I haven't seen a response regarding my question about readme.md

Please wait with merge for all reviewers then :) However, I've read that part about facade and it's pretty awesome work. Thanks @coditive-przemek-h 

---

> I've also created some new issues, because I see that we still have some work to do to adjust this to our workflow.
That's cool 💪 I'll review them in the following days. Maybe it would be good to use github projects, te stay on track with everything: https://github.com/orgs/coditive-com/projects/2/views/2 - just a thing to consider :)
