### ISSUE TITLE
README.md missing word - hooks description

### ISSUE THREAD

**Issue by coditive-filip-c** [coditive-com/firestarter-theme#37]
I think there's a missing word in the general README, at Hooks description: `Coditive theme a custom way for firing the WordPress hooks`. Probably should be something like `Coditive theme uses/has a custom way for firing the WordPress hooks`.

**Comment by coditive-tomek-g** [comment]
Fixed here - https://github.com/coditive-com/firestarter-theme/commit/37f819040495de95c79853ad7d5837aa459edc1c
