### ISSUE TITLE
Translate:pot doesn't work for blade tags

### ISSUE THREAD

**Issue by coditive-tomek-g** [coditive-com/firestarter-theme#39]
I noticed that the `yarn translate:pot` command doesn't work correctly. The generated file `/resources/lang/sage.pot` contains strings only from the `/app` folder - but not all the strings that I have added in my templates in the ‘/resources` folder.

I made some research and this problem is connected to the blade tags, if I used `<?php __('Text test', 'textdomain'); ?>` then the generated `.pot` file contains `Text test` string, but when I used blade tags `{{ }}` or `{!! !!}` then the strings are not included in the `.pot`.

I found a solution, but I don't know if it's a good solution, maybe you have a better idea - if we modify the `translate: pot` command to:

```
"translate:pot": "wp acorn view:cache && wp i18n make-pot ../../ ./resources/lang/sage.pot --ignore-domain --include=\"themes/firestarter-theme/app,themes/firestarter-theme/resources,cache/acorn/framework/views\" --exclude=\"themes/firestarter-theme/public,plugins,languages,upgrade,uploads,index.php\"",
```

then everything works correctly because we also included the `views` folder from the cache, where the blade tags are changed to the `php` tags. As I said, it works, but maybe can we make this command shorthanded in some way? Additionally, this command contains the theme folder name, so if someone changes the theme directory, then the command needs to be updated also, so it's not nice. 

@coditive-michal-s @coditive-przemek-h - What do you think about it?

**Comment by coditive-tomek-g** [comment]
Additional info - the updated command doesn't work well for the blocks templates, because `wp acorn view:cache` doesn't create cached views for the blocks templates. Because of it, the translation strings from the blocks are not included in the pot file. We can just remove this part of the command but then we should have an option to generate automatically the "cache" version for each template.

**Comment by coditive-michal-s** [comment]
@coditive-tomek-g 

I'm running WP CLI 2.7.1 and everything seems to be working fine 🤔 

I've done some digging and it seems that you were kinda unlucky since literally on the day you created this issue a [new version of WP CLI was released which, according to the changelog, added support for blade files](https://make.wordpress.org/cli/2022/10/11/wp-cli-v2-7-0-release-notes/). Could you update the CLI and let me know if everything works fine now?

```
wp cli update
```

**Comment by coditive-tomek-g** [comment]
@coditive-michal-s 
It looks like you're right! I've updated WP CLI to 2.7.1 and everything works fine, thanks!
