### ISSUE TITLE
Migrate frontend layer from sage 9 to 10

### ISSUE THREAD

**Issue by coditive-pawel-m** [coditive-com/firestarter-theme#5]

**Comment by coditive-pawel-m** [comment]
@coditive-tomek-g @coditive-przemek-h 
are we good to close this issue?

**Comment by coditive-przemek-h** [comment]
As I remember Tomasz asked for the options page for creating a logo assignment. It will be ready after we merge my last changes. But I think that we can add a new issue for this.
